app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),  
    path('passengers/', include('passengers.urls', namespace='passengers')),
    path('personal/', include('personal.urls', namespace='personal')),
    path('applications/', include('applications.urls', namespace='applications')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG: 
	urlpatterns += [
		path("__debug__/", include("debug_toolbar.urls")),
    ]

personal/urls.py
from django.urls import path, include
from . import views

app_name = 'personal'

urlpatterns = [
    path('', views.add_personal_and_shift, name='personal'),
    path('personal-list/', views.personal_list, name='personal_list'),
    path('shift-list/', views.shift_list, name='shift_list'),
]

personal/models.py
from django.db import models

class Personal(models.Model):
    MALE = 'Мужской'
    FEMALE = 'Женский'
    GENDER_CHOICES = [
        (MALE, 'Мужской'),
        (FEMALE, 'Женский'),
    ]
    UCHASTOK_CHOICES = [
        ('ЦУ-1', 'ЦУ-1'),
        ('ЦУ-2', 'ЦУ-2'),
        ('ЦУ-3', 'ЦУ-3'),
        ('ЦУ-3(Н)', 'ЦУ-3(Н)'),
        ('ЦУ-4', 'ЦУ-4'),
        ('ЦУ-4(Н)', 'ЦУ-4(Н)'),
        ('ЦУ-5', 'ЦУ-5'),
        ('ЦУ-8', 'ЦУ-8'),
    ]
    RANK_CHOICES = [
        ('ЦУ', 'Начальник участка'),
        ('ЦСИ', 'Старший инспектор'),
        ('ЦИО', 'Оператор'),
        ('ЦИ', 'Инспектор'),
        ('Администратор', 'Администратор'),
        ('Специалист', 'Специалист'),
    ]
    TIME_WORK_CHOICES = {
        'ЦУ-1': ('7:00 - 19:00', '8:00 - 20:00'),
        'ЦУ-2': ('7:00 - 19:00', '8:00 - 20:00'),
        'ЦУ-3': ('7:00 - 19:00', '8:00 - 20:00', '10:00 - 22:00'),
        'ЦУ-3(Н)': ['20:00 - 8:00'],
        'ЦУ-4': ('7:00 - 19:00', '8:00 - 20:00', '10:00 - 22:00'),
        'ЦУ-4(Н)': ['20:00 - 8:00'],
        'ЦУ-5': ('7:00 - 19:00', '8:00 - 20:00', '10:00 - 22:00'),
        'ЦУ-8': ('7:00 - 19:00', '8:00 - 20:00')
    }
    SMENA_CHOICES = [
        ('1', '1'),
        ('2', '2'),
        ('1Н', '1Н'),
        ('2Н', '2Н'),
        ('5', '5'),
    ]
    ID = models.AutoField(primary_key=True, verbose_name='ID')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия', blank=True, null=True)
    first_name = models.CharField(max_length=255, verbose_name='Имя', blank=True, null=True)
    second_name = models.CharField(max_length=255, blank=True, null=True, verbose_name='Отчество')
    FIO = models.CharField(max_length=255, verbose_name='ФИО')
    UCHASTOK = models.CharField(max_length=10, blank=True, null=True, verbose_name='Участок работы',choices= UCHASTOK_CHOICES)
    SEX = models.CharField(max_length=10, verbose_name='Пол', choices=GENDER_CHOICES)
    TIME_WORK = models.CharField(max_length=100, verbose_name='Время работы')
    SMENA = models.CharField(max_length=100, verbose_name='Смена',choices= SMENA_CHOICES)
    RANK = models.CharField(max_length=100, verbose_name='Должность', choices=RANK_CHOICES)
    DATE = models.DateField(verbose_name='Дата')
    t_n = models.CharField(max_length=8, blank=True, null=True, verbose_name='Табельный номер')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    t_tel = models.CharField(max_length=12, blank=True, null=True, verbose_name='Рабочий телефон')
    r_tel = models.CharField(max_length=12, blank=True, null=True, verbose_name='Личный телефон')
    zdo = models.BooleanField(blank=True, null=True, verbose_name='Может ли сотрудник выполнять тяжелую работу')

    class Meta:
        db_table = 'Personal'
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        
    def __str__(self):
        return f'{self.ID}: {self.FIO or f"{self.last_name} {self.first_name} {self.second_name}".strip()}'
    
class Shift(models.Model):
    twb_CHOICES = [
        ('7:00 - 19:00', '7:00 - 19:00'),
        ('8:00 - 20:00', '8:00 - 20:00'),
        ('10:00 - 22:00', '10:00 - 22:00'),
        ('20:00 - 8:00', '20:00 - 8:00'),
    ]

    id_SMENA = models.AutoField(primary_key=True, verbose_name='ID')
    id_insp = models.ForeignKey(Personal, blank=True, null=True, to_field='ID', on_delete=models.CASCADE)
    SMENA = models.CharField(max_length=100, verbose_name='Смена',choices= Personal.SMENA_CHOICES)
    date = models.DateField(verbose_name='Дата выхода')
    time_work_begin =  models.CharField(max_length=50, blank=True, null=True,verbose_name='Время работы',choices= twb_CHOICES)


    class Meta:
        db_table = 'Shift'
        verbose_name = 'Смена'
        verbose_name_plural = 'Смены'

    def __str__(self):
        return f'Смена {self.SMENA} - Сотрудник {self.id_insp}'

personal/forms.py
from django import forms
from .models import Personal, Shift

# # class TimeRangeWidget(forms.MultiWidget):
#     def __init__(self, attrs=None):
#         widgets = [
#             forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
#             forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
#         ]
#         super().__init__(widgets, attrs)

#     def decompress(self, value):
#         if value:
#             return value.split('-')
#         return [None, None]

#     def format_output(self, rendered_widgets):
#         return '{} - {}'.format(*rendered_widgets)

# class TimeRangeField(forms.MultiValueField):
#     widget = TimeRangeWidget

#     def __init__(self, *args, **kwargs):
#         fields = [
#             forms.TimeField(),
#             forms.TimeField(),
#         ]
#         super().__init__(fields, *args, **kwargs)

#     def compress(self, data_list):
#         if data_list:
#             return '{}-{}'.format(*data_list)
#         return ''

class PersonalForm(forms.ModelForm):
    class Meta:
        model = Personal
        fields = [
            'last_name', 'first_name', 'second_name', 'UCHASTOK', 'SEX', 'TIME_WORK', 'SMENA', 'RANK', 'DATE', 't_n', 'description', 't_tel', 'r_tel', 'zdo'
        ]
        widgets = {
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'second_name': forms.TextInput(attrs={'class': 'form-control'}),
            'UCHASTOK': forms.Select(attrs={'class': 'form-control', 'id': 'uchastok-select'}),
            'SEX': forms.Select(attrs={'class': 'form-control'}),
            'TIME_WORK': forms.Select(attrs={'class': 'form-control', 'id': 'time-work-select'}),
            'SMENA': forms.Select(attrs={'class': 'form-control'}),
            'RANK': forms.Select(attrs={'class': 'form-control'}),
            'DATE': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            't_n': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            't_tel': forms.TextInput(attrs={'class': 'form-control'}),
            'r_tel': forms.TextInput(attrs={'class': 'form-control'}),
            'zdo': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

    def save(self, commit=True):
        instance = super(PersonalForm, self).save(commit=False)
        first_initial = instance.first_name[0] + '.' if instance.first_name else ''
        second_initial = instance.second_name[0] + '.' if instance.second_name else ''
        instance.FIO = f'{instance.last_name} {first_initial}{second_initial}'.strip()
        if commit:
            instance.save()
        return instance


class ShiftForm(forms.ModelForm):
    id_insp = forms.ModelChoiceField(
        queryset=Personal.objects.all(),
        label="ID Сотрудника",
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Shift
        fields = ['id_insp', 'SMENA', 'date', 'time_work_begin']
        widgets = {
            'id_insp': forms.Select(attrs={'class': 'form-control'}),
            'SMENA': forms.Select(attrs={'class': 'form-control'}),
            'date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'time_work_begin': forms.Select(attrs={'class': 'form-control'}),
        }

personal/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Personal, Shift
from .forms import PersonalForm, ShiftForm
from django.contrib.auth.decorators import login_required

@login_required
def add_personal_and_shift(request):
    if request.method == 'POST':
        if 'personal_form' in request.POST:
            personal_form = PersonalForm(request.POST)
            if personal_form.is_valid():
                personal_form.save()
                return JsonResponse({'success': True})
            else:
                errors = personal_form.errors
                return JsonResponse({'success': False, 'errors': errors}, status=400)

        elif 'shift_form' in request.POST:
            shift_form = ShiftForm(request.POST)
            if shift_form.is_valid():
                shift_form.save()
                return JsonResponse({'success': True})
            else:
                errors = shift_form.errors
                return JsonResponse({'success': False, 'errors': errors}, status=400)
    else:
        personal_form = PersonalForm()
        shift_form = ShiftForm()
    
    personal_list = Personal.objects.all()
    shift_list = Shift.objects.all()
    
    context = {
        'personal_form': personal_form,
        'shift_form': shift_form,
        'personal_list': personal_list,
        'shift_list': shift_list,
    }
    return render(request, 'personal/personal.html', context)

@login_required
def personal_list(request):
    personals = Personal.objects.all().values('ID', 'FIO', 'UCHASTOK', 'SEX', 'TIME_WORK', 'SMENA', 'RANK', 'DATE', 't_n', 'description', 't_tel', 'r_tel', 'zdo')
    return JsonResponse(list(personals), safe=False)

@login_required
def shift_list(request):
    shifts = Shift.objects.all().values('id_SMENA', 'id_insp', 'SMENA', 'date', 'time_work_begin')
    return JsonResponse(list(shifts), safe=False)

personal/templates/personal/personal.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-fluid" style="min-height: 80vh">
    <div class="row">
        <!-- Column for "Добавить сотрудника" and "Сотрудники" table -->
        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-body text-center">
                    <h2 class="card-title">Добавить сотрудника</h2>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPersonalModal">Добавить сотрудника</button>
                </div>
            </div>
            <div class="card mb-3">
                <div class="card-body">
                    <h2 class="card-title">Сотрудники</h2>
                    <div class="table-responsive" style="max-height: 400px; overflow-y: auto">
                        <table class="table table-striped" id="personal-table">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>ФИО</th>
                                    <th>Участок работы</th>
                                    <th>Пол</th>
                                    <th>Время работы</th>
                                    <th>Смена</th>
                                    <th>Должность</th>
                                    <th>Дата</th>
                                    <th>Табельный номер</th>
                                    <th>Описание</th>
                                    <th>Рабочий телефон</th>
                                    <th>Личный телефон</th>
                                    <th>Тяжелая работа</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for personal in personal_list %}
                                <tr>
                                    <td>{{ personal.ID }}</td>
                                    <td>{{ personal.FIO }}</td>
                                    <td>{{ personal.UCHASTOK }}</td>
                                    <td>{{ personal.SEX }}</td>
                                    <td>{{ personal.TIME_WORK }}</td>
                                    <td>{{ personal.SMENA }}</td>
                                    <td>{{ personal.RANK }}</td>
                                    <td>{{ personal.DATE }}</td>
                                    <td>{{ personal.t_n }}</td>
                                    <td>{{ personal.description }}</td>
                                    <td>{{ personal.t_tel }}</td>
                                    <td>{{ personal.r_tel }}</td>
                                    <td>{{ personal.zdo }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <!-- Column for "Добавить смену" and "Смены" table -->
        <div class="col-md-4">
            <div class="card mb-3">
                <div class="card-body text-center">
                    <h2 class="card-title">Добавить смену</h2>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addShiftModal">Добавить смену</button>
                </div>
            </div>
            <div class="card mb-3">
                <div class="card-body">
                    <h2 class="card-title">Смены</h2>
                    <div class="table-responsive" style="max-height: 400px; overflow-y: auto">
                        <table class="table table-striped" id="shift-table">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>ID Сотрудника</th>
                                    <th>Смена</th>
                                    <th>Дата выхода</th>
                                    <th>Время работы</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for shift in shift_list %}
                                <tr>
                                    <td>{{ shift.id_SMENA }}</td>
                                    <td>{{ shift.id_insp.ID }}</td>
                                    <td>{{ shift.SMENA }}</td>
                                    <td>{{ shift.date }}</td>
                                    <td>{{ shift.time_work_begin }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Модальное окно для формы "Добавить сотрудника" -->
<div class="modal fade" id="addPersonalModal" tabindex="-1" aria-labelledby="addPersonalModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addPersonalModalLabel">Добавить сотрудника</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="personalForm" method="post">
                    {% csrf_token %} {{ personal_form.as_p }}
                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary">Сохранить сотрудника</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Модальное окно для формы "Добавить смену" -->
<div class="modal fade" id="addShiftModal" tabindex="-1" aria-labelledby="addShiftModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addShiftModalLabel">Добавить смену</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="shiftForm" method="post">
                    {% csrf_token %} {{ shift_form.as_p }}
                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary">Сохранить смену</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="successModalLabel">Успешно</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">Данные были успешно сохранены.</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<!-- Подключаем локальный файл jQuery -->
<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $("#personalForm").on("submit", function (e) {
            e.preventDefault();

            $.ajax({
                type: "POST",
                url: "",
                data: $(this).serialize() + "&personal_form=1",
                success: function (response) {
                    $("#addPersonalModal").modal("hide");
                    $("#successModal").modal("show");

                    // Обновление таблицы сотрудников
                    updatePersonalTable();
                },
                error: function (response) {
                    let errorMessage = "Ошибка при добавлении сотрудника.\n";
                    if (response.responseJSON && response.responseJSON.errors) {
                        $.each(response.responseJSON.errors, function (field, errors) {
                            errorMessage += `${field}: ${errors.join(", ")}\n`;
                        });
                    }
                    alert(errorMessage);
                },
            });
        });

        $("#shiftForm").on("submit", function (e) {
            e.preventDefault();

            $.ajax({
                type: "POST",
                url: "",
                data: $(this).serialize() + "&shift_form=1",
                success: function (response) {
                    $("#addShiftModal").modal("hide");
                    $("#successModal").modal("show");

                    // Обновление таблицы смен
                    updateShiftTable();
                },
                error: function (response) {
                    let errorMessage = "Ошибка при добавлении смены.\n";
                    if (response.responseJSON && response.responseJSON.errors) {
                        $.each(response.responseJSON.errors, function (field, errors) {
                            errorMessage += `${field}: ${errors.join(", ")}\n`;
                        });
                    }
                    alert(errorMessage);
                },
            });
        });

        function updatePersonalTable() {
            $.ajax({
                url: "{% url 'personal:personal_list' %}", // Убедитесь, что у вас есть такой URL
                type: "GET",
                success: function (data) {
                    var personalTableBody = $("#personal-table tbody");
                    personalTableBody.empty();
                    data.forEach(function (personal) {
                        personalTableBody.append(`
                            <tr>
                                <td>${personal.ID}</td>
                                <td>${personal.FIO}</td>
                                <td>${personal.UCHASTOK}</td>
                                <td>${personal.SEX}</td>
                                <td>${personal.TIME_WORK}</td>
                                <td>${personal.SMENA}</td>
                                <td>${personal.RANK}</td>
                                <td>${personal.DATE}</td>
                                <td>${personal.t_n}</td>
                                <td>${personal.description}</td>
                                <td>${personal.t_tel}</td>
                                <td>${personal.r_tel}</td>
                                <td>${personal.zdo}</td>
                            </tr>
                        `);
                    });
                },
                error: function () {
                    alert("Ошибка при обновлении таблицы сотрудников.");
                },
            });
        }

        function updateShiftTable() {
            $.ajax({
                url: "{% url 'personal:shift_list' %}", // Убедитесь, что у вас есть такой URL
                type: "GET",
                success: function (data) {
                    var shiftTableBody = $("#shift-table tbody");
                    shiftTableBody.empty();
                    data.forEach(function (shift) {
                        shiftTableBody.append(`
                            <tr>
                                <td>${shift.id_SMENA}</td>
                                <td>${shift.id_insp}</td>
                                <td>${shift.SMENA}</td>
                                <td>${shift.date}</td>
                                <td>${shift.time_work_begin}</td>
                            </tr>
                        `);
                    });
                },
                error: function () {
                    alert("Ошибка при обновлении таблицы смен.");
                },
            });
        }

        const timeWorkChoices = {
            "ЦУ-1": ["7:00 - 19:00", "8:00 - 20:00"],
            "ЦУ-2": ["7:00 - 19:00", "8:00 - 20:00"],
            "ЦУ-3": ["7:00 - 19:00", "8:00 - 20:00", "10:00 - 22:00"],
            "ЦУ-3(Н)": ["20:00 - 8:00"],
            "ЦУ-4": ["7:00 - 19:00", "8:00 - 20:00", "10:00 - 22:00"],
            "ЦУ-4(Н)": ["20:00 - 8:00"],
            "ЦУ-5": ["7:00 - 19:00", "8:00 - 20:00", "10:00 - 22:00"],
            "ЦУ-8": ["7:00 - 19:00", "8:00 - 20:00"],
        };

        $("#uchastok-select").change(function () {
            const uchastok = $(this).val();
            const timeWorkSelect = $("#time-work-select");
            timeWorkSelect.empty();

            if (uchastok in timeWorkChoices) {
                timeWorkChoices[uchastok].forEach(function (timeRange) {
                    timeWorkSelect.append(new Option(timeRange, timeRange));
                });
            }
        });

        $("#uchastok-select").trigger("change");
    });
</script>
{% endblock content %}