app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),  
    path('passengers/', include('passengers.urls', namespace='passengers')),
    path('personal/', include('personal.urls', namespace='personal')),
    path('applications/', include('applications.urls', namespace='applications')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG: 
	urlpatterns += [
		path("__debug__/", include("debug_toolbar.urls")),
    ]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
	path('login/', views.login, name="login"),
	path('registration/', views.registration, name="registration"),
	path('profile/', views.profile, name="profile"),
	path('logout/', views.logout, name="logout"),
]

users/models.py
# models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from personal.models import Personal

class User(AbstractUser):
    USER_ROLES = [
        ('employee', 'Сотрудник'),
        ('operator', 'Оператор'),
        ('admin', 'Администратор'),
    ]
    
    role = models.CharField(max_length=10, choices=USER_ROLES, default='employee')
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    id_s = models.ForeignKey(Personal, blank=True, null=True, to_field='ID', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователи'
        verbose_name_plural = 'Пользователи'
    
    def __str__(self):
         return self.username

users/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()
    
    class Meta:
        model = User

class UserRegistrationForm(UserCreationForm):
    USER_ROLES = [
        ('employee', 'Сотрудник'),
        ('operator', 'Оператор'),
        ('admin', 'Администратор'),
    ]
    
    role = forms.ChoiceField(choices=USER_ROLES, required=True)
  
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
            "role",
        ]
  
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
        )

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
# views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from .forms import ProfileForm, UserLoginForm, UserRegistrationForm
from .models import User
from personal.models import Personal
from main.models import Personalapplication
def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()
    
    context = {
        "title": "Авторизация",
        'form': form,
    }
    return render(request, 'users/login.html', context)

def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
    
    context = {
        "title": "Регистрация",
        'form': form,
    }
    return render(request, 'users/registration.html', context)

@login_required
def profile(request):
    if request.method == "POST":
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = ProfileForm(instance=request.user)
        
    # Получение роли пользователя
    role_s = request.user.role

    # Получение активных заявок для текущего пользователя
    x = request.user.id_s
    
    active_applications = Personalapplication.objects.filter(person=request.user.id_s)

    context = {
        "title": "Профиль",
        'form': form,
        'role_s': role_s,
        'active_applications': active_applications,
        'x': x,
    }
    return render(request, 'users/profile.html', context)

@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('main:index'))

users/templates/users/login.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
	<div class="row mt-1">
		<div class="col-lg-2">
			<!-- Пустой блок на усмотрение -->
		</div>
		<div class="col-lg-10">
			<!-- Контент на странице -->
			<div class="row">
				<div class="container mt-5">
					<div class="row justify-content-center">
						<div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
							<h2 class="text-center mb-4">Авторизация</h2>
							<form action="{% url "user:login" %}" method="post">
								{% csrf_token %}
								
								<div class="mb-3">
									<label for="id_username" class="form-label"
										>Имя пользователя</label
									>
									<input
										type="text"
										class="form-control"
										value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
										name="username"
										id="id_username"
										placeholder="Введите ваше имя пользователя"
										required
									/>

								</div>
								<div class="mb-3">
									<label for="id_password" class="form-label">Пароль</label>
									<input
										type="password"
										class="form-control"
										name="password"
										id="id_password"
										placeholder="Введите ваш пароль"
										required
									/>
								</div> 
							
									

								
								<button type="submit" class="btn btn-dark btn-block">
									Войти
								</button>
							</form>
							<div class="mt-3">
								<a href="#">Забыли пароль?</a>
								<a href={% url "user:registration" %}>Создать аккаунт</a>
							</div>
							<hr />
							<div class="text-center">
								<p>Или авторизуйтесь через:</p>
								<a href="#" class="btn btn-dark">
									<img
										class="mx-1"
										src=""
										alt="Catalog Icon"
										width="16"
										height="16"
									/>
									Telegram
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

users/templates/users/profile.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-fluid px-0">
    <div class="row mt-1 mx-0">
        <div class="col-lg-2 d-none d-lg-block">
            <!-- Пустой блок на усмотрение -->
        </div>
        <div class="col-lg-10 col-12">
            <!-- Контент на странице -->
            <div class="row">
                <div class="container mt-5">
                    <div class="row">
                        <!-- Профиль с данными пользователя -->
                        <div class="col-md-5 col-12">
                            <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                <h3 class="text-center mb-4">Профиль пользователя</h3>
                                <form action="{% url 'users:profile' %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-12 mb-3 text-center">
                                            {% if user.image %}
                                            <img src="{{ user.image.url }}" alt="Аватар пользователя" class="img-fluid rounded-circle" style="max-width: 150px" />
                                            {% else %}
                                            <img src="{% static 'images/baseavatar.jpg' %}" alt="Аватар пользователя" class="img-fluid rounded-circle" style="max-width: 150px" />
                                            {% if form.image.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                            {% endif %} {% endif %}

                                            <input type="file" class="form-control mt-3" id="id_image" name="image" accept="image/*" />
                                        </div>
                                        <div class="col-md-12 mb-3">
                                            <label for="id_first_name" class="form-label">Имя*</label>
                                            <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="Введите ваше имя" value="{{ form.first_name.value }}" required />
                                            {% if form.first_name.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                            {% endif %}
                                        </div>
                                        <div class="col-md-12 mb-3">
                                            <label for="id_last_name" class="form-label">Фамилия*</label>
                                            <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Введите вашу фамилию" value="{{ form.last_name.value }}" required />
                                            {% if form.last_name.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                            {% endif %}
                                        </div>
                                        <div class="col-md-12 mb-3">
                                            <label for="id_username" class="form-label">Имя пользователя*</label>
                                            <input type="text" class="form-control" id="id_username" name="username" placeholder="Введите ваше отчество" value="{{ form.username.value }}" required />
                                            {% if form.username.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-dark">Сохранить</button>
                                </form>
                            </div>
                        </div>
                        <!-- Активная заявка -->
                        {% comment %}
                        <div class="col-md-7 col-12">
                            <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                <h3 class="text-center mb-4">Активная заявка {{ active_applications }} xxxxxxx{{ x }} zzzzz{{ active_applications }}</h3>
                                <div class="container" id="cart-items-container">
                                    {% for application in active_applications %}
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Активная заявка #{{ application.application.id }}</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col-md-4"><strong>Статус:</strong></div>
                                                    <div class="col-md-8">{{ application.application.status }}</div>
                                                </div>
                                                <div class="row text-center">
                                                    <div class="col-md-4"><strong>Дата и время начала:</strong></div>
                                                    <div class="col-md-8">{{ application.application.datetime }}</div>
                                                </div>
                                                <div class="row text-center">
                                                    <div class="col-md-4"><strong>Время встречи с пассажиром:</strong></div>
                                                    <div class="col-md-8">{{ application.application.time3 }}</div>
                                                </div>
                                                <div class="row text-center">
                                                    <div class="col-md-4"><strong>Время исполнения заявки:</strong></div>
                                                    <div class="col-md-8">{{ application.application.time4 }}</div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    {% empty %}
                                    <p class="text-center">Нет активных заявок.</p>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        {% endcomment %}
                        <!-- Оформленные Заявки -->
                        <div class="col-12">
                            <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                <h3 class="text-center mb-4">Мои заявки</h3>
                                <!-- Разметка Заявки -->
                                <div class="container">
                                    <div class="accordion" id="accordionExample">
                                        <div class="accordion-item">
                                            <h2 class="accordion-header" id="heading1">
                                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">Заявка № 134 - 7 сентября 2024 19:24 | Статус:<strong class="mx-2">В обработке</strong></button>
                                            </h2>
                                            <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                                <div class="accordion-body">
                                                    <table class="table table-dark table-hover">
                                                        <thead>
                                                            <tr>
                                                                <th>Наименование заявки</th>
                                                                <th>Станция</th>
                                                                <th>Время</th>
                                                                <th>Пассажир</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td><a class="text-white" href="#">Временно маломобильные</a></td>
                                                                <td>Воробьёвы горы</td>
                                                                <td>22:10</td>
                                                                <td>Петров Илья Назарович</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                    <div class="d-flex justify-content-between">
                                                        <p><strong>Примечание:</strong></p>
                                                        <p><strong>Может опоздать</strong></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="accordion-item">
                                            <h2 class="accordion-header" id="heading2">
                                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">Заявка № 104 - 5 марта 2024 11:42 Статус:<strong class="mx-2">Выполнено</strong></button>
                                            </h2>
                                            <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                                <div class="accordion-body">
                                                    <table class="table table-dark table-hover">
                                                        <thead>
                                                            <tr>
                                                                <th>Наименование заявки</th>
                                                                <th>Станция</th>
                                                                <th>Время</th>
                                                                <th>Пассажир</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td><a class="text-white" href="#">Инвалид по слуху</a></td>
                                                                <td>Чистые пруды</td>
                                                                <td>15:20</td>
                                                                <td>Белов Павел Анатольевич</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                    <div class="d-flex justify-content-between">
                                                        <p><strong>Примечание:</strong></p>
                                                        <p><strong>Любит прятаться</strong></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Закончилась разметка Заявки -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row mt-1">
        <div class="col-lg-2">
            <!-- Пустой блок на усмотрение -->
        </div>
        <div class="col-lg-10">
            <!-- Контент на странице -->
            <div class="row">
                <div class="container mt-5">
                    <div class="row justify-content-center">
                        <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                            <h2 class="text-center mb-4">Регистрация</h2>
                            <form action="{% url 'users:registration' %}" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 mb-3">
                                        <label for="id_first_name" class="form-label">Имя*</label>
                                        <input type="text" class="form-control" id="id_first_name"
                                               value="{{ form.first_name.value|default_if_none:'' }}" name="first_name"
                                               placeholder="Введите ваше имя" required>
                                        {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <label for="id_last_name" class="form-label">Фамилия*</label>
                                        <input type="text" class="form-control" id="id_last_name"
                                               value="{{ form.last_name.value|default_if_none:'' }}" name="last_name"
                                               placeholder="Введите вашу фамилию" required>
                                        {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <label for="id_username" class="form-label">Имя пользователя*</label>
                                        <input type="text" class="form-control" id="id_username"
                                               value="{{ form.username.value|default_if_none:'' }}" name="username"
                                               placeholder="Введите ваше имя пользователя" required>
                                        {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <label for="id_email" class="form-label">Email*</label>
                                        <input type="email" class="form-control" id="id_email"
                                               value="{{ form.email.value|default_if_none:'' }}" name="email"
                                               placeholder="Введите ваш email" required>
                                        {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <label for="id_password1" class="form-label">Пароль*</label>
                                        <input type="password" class="form-control" id="id_password1" name="password1"
                                               placeholder="Введите пароль" required>
                                        {% if form.password1.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                        <input type="password" class="form-control" id="id_password2" name="password2"
                                               placeholder="Подтвердите пароль" required>
                                        {% if form.password2.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-12 mb-3">
                                        <label for="id_role" class="form-label">Роль*</label>
                                        <select class="form-control" id="id_role" name="role" required>
                                            {% for value, display in form.role.field.choices %}
                                                <option value="{{ value }}" {% if form.role.value == value %}selected{% endif %}>
                                                    {{ display }}
                                                </option>
                                            {% endfor %}
                                        </select>
                                        {% if form.role.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.role.errors }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-dark btn-block">Зарегистрироваться</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}