app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),  
    path('passengers/', include('passengers.urls', namespace='passengers')),
    path('personal/', include('personal.urls', namespace='personal')),
    path('applications/', include('applications.urls', namespace='applications')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG: 
	urlpatterns += [
		path("__debug__/", include("debug_toolbar.urls")),
    ]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('distribute-tasks/', views.distribute_tasks, name='distribute_tasks'),
    path('run-scheduler/', views.run_scheduler, name='run_scheduler'),  # Новый маршрут для запуска планировщика
]

passengers/urls.py
from django.urls import path
from . import views

app_name = 'passengers'

urlpatterns = [
    path('', views.add_passenger, name='passengers'),
    path('success/', views.success_view, name='success'),
]

personal/urls.py
from django.urls import path, include
from . import views

app_name = 'personal'

urlpatterns = [
    path('', views.add_personal_and_shift, name='personal'),
    path('personal-list/', views.personal_list, name='personal_list'),
    path('shift-list/', views.shift_list, name='shift_list'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
	path('login/', views.login, name="login"),
	path('registration/', views.registration, name="registration"),
	path('profile/', views.profile, name="profile"),
	path('logout/', views.logout, name="logout"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'base/css/base.css' %}" />
        <link rel="stylesheet" href="{% static 'base/css/styles.css' %}" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand text-green" href="{% url 'main:index' %}">Home</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'user:login' %}">Войти</a>
                            </li>
                            {% else %} {% if user_role == 'admin' or user_role == 'operator' or user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link text-white" aria-current="page" href="{% url 'passengers:passengers' %}">Пассажиры</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" aria-current="page" href="{% url 'personal:personal' %}">Сотрудники</a>
                            </li>

                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link text-white" aria-current="page" href="{% url 'applications:applications' %}">Заявки</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Мой профиль </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item text-black" href="{% url 'user:profile' %}">Личный кабинет</a>
                                    </li>
                                    {% if user.is_admin or user.is_superuser %}
                                    <li>
                                        <a class="dropdown-item text-black" href="{% url 'admin:index' %}">Админ панель</a>
                                    </li>
                                    {% endif %}
                                    <li><hr class="dropdown-divider" /></li>
                                    <li>
                                        <a class="dropdown-item text-black" href="{% url 'user:logout' %}">Выйти</a>
                                    </li>
                                </ul>
                            </li>
                            {% endif %}
                        </ul>
                        <form class="d-flex" role="search">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                            <button class="btn btn-outline-success" type="submit">
                                <img src="{% static 'main/icons/search.svg' %}" alt="S" />
                            </button>
                        </form>
                    </div>
                </div>
            </nav>
        </header>

        <section class="container-fluid">{% include 'includes/notifications.html' %} {% block content %}{% endblock content %}</section>

        <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>