app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),  
    path('passengers/', include('passengers.urls', namespace='passengers')),
    path('personal/', include('personal.urls', namespace='personal')),
    path('applications/', include('applications.urls', namespace='applications')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG: 
	urlpatterns += [
		path("__debug__/", include("debug_toolbar.urls")),
    ]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('distribute-tasks/', views.distribute_tasks, name='distribute_tasks'),
    path('run-scheduler/', views.run_scheduler, name='run_scheduler'),  # Новый маршрут для запуска планировщика
]

main/models.py
from django.db import models
from personal.models import Personal
from applications.models import Application

class Personalapplication(models.Model):
    id_pa = models.AutoField(primary_key=True)
    person = models.ForeignKey(Personal, related_name='person', on_delete=models.CASCADE, verbose_name='Сотрудник', to_field='ID')
    application = models.ForeignKey(Application, related_name='application', on_delete=models.CASCADE, verbose_name='Заявка', to_field='id')

    class Meta:
        db_table = 'Personalapplication'
        verbose_name = 'Заявки сотрудника'
        verbose_name_plural = 'Заявки сотрудника'
        
    def __str__(self):
        return f'Заявка {self.application.id} для сотрудника {self.person.FIO}'
        verbose_name_plural = 'Заявки сотрудника'

main/views.py
import json
import os
import sys
from django.http import JsonResponse
from django.shortcuts import render
from .models import Personalapplication
from metro.models import Stationtime, Transfertime
from model import routes
from personal.models import Personal
from applications.models import Application

def index(request):
    station_times = Stationtime.objects.all().values('id_st1', 'id_st2', 'time')
    transfer_times = Transfertime.objects.all().values('id1', 'id2', 'time')
    id_person = list(Personal.objects.all().values_list('ID', flat=True))
    id_applic = list(Application.objects.all().values_list('id', flat=True))

    if not id_person or not id_applic:
        raise ValueError("Оба списка id_person и id_applic должны содержать данные.")

    combined_list = []
    i, j = 0, 0

    while j < len(id_applic):
        combined_list.append((i + 1, id_person[i % len(id_person)], id_applic[j]))
        i += 1
        j += 1
    
    vertexes = []
    for record in station_times:
        vertexes.append({
            'id_st1': record['id_st1'],
            'id_st2': record['id_st2'],
            'time': str(record['time'])
        })
    for record in transfer_times:
        vertexes.append({
            'id1': record['id1'],
            'id2': record['id2'],
            'time': str(record['time'])
        })
        
    routes_instance = routes.Routes(vertexes)
    # print(vertexes)
    distance = None
    shortest_path = None
    
    for record in vertexes:
        try:
            if 'id_st1' in record and 'id_st2' in record:
                distance = routes_instance.CalcDistance(int(record['id_st1']), int(record['id_st2']))
            elif 'id1' in record and 'id2' in record:
                shortest_path = routes_instance.CreateShortestPath(int(record['id1']), int(record['id2']))
        except nx.NetworkXNoPath:
            distance = float('inf')
        except nx.NodeNotFound as e:
            print(f"Ошибка: {e}")

    personal_applications = Personalapplication.objects.select_related('person', 'application').all()
    context = {
        'personal_applications': personal_applications,
        'result': combined_list,
    }
    return render(request, 'main/index.html', context)

sys.path.append(os.path.join(os.path.dirname(__file__), '../model'))

import routes, schedule


def distribute_tasks(request):
    # Загрузите данные из файлов
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    with open(os.path.join(script_dir, '../model/subwey.json'), 'r', encoding='utf-8') as f:
        pointersJs = json.load(f)
    
    with open(os.path.join(script_dir, '../model/switch.json'), 'r', encoding='utf-8') as f:
        switchJs = json.load(f)
    
    with open(os.path.join(script_dir, '../model/staffs.json'), 'r', encoding='utf-8') as f:
        staffsJs = json.load(f)
    
    with open(os.path.join(script_dir, '../model/requests.json'), 'r', encoding='utf-8') as f:
        requestsJs = json.load(f)
    
    # Объедините данные и выполните вычисления
    map_data = pointersJs + switchJs
    graph = routes.Routes(map_data)
    distance = graph.CalcDistance(65, 87)
    
    data = {
        'requests': requestsJs,
        'staffs': staffsJs
    }
    scheduler = schedule.Scheduler(data, graph)
    schedule_result = scheduler.CreateSchedule()
    
    # Преобразуйте результат в нужный формат
    result = []
    for i, (id_person, id_applic) in enumerate(schedule_result.items(), start=1):
        result.append({'num': i, 'id_person': id_person, 'id_applic': id_applic})
    
    # Верните результат в формате JSON
    return JsonResponse({
        'result': result
    })

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<h1>Заявки сотрудников</h1>

<div class="table-responsive" style="max-height: 400px; overflow-y: auto">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Номер</th>
                <th>ID сотрудника</th>
                <th>ID заявки</th>
            </tr>
        </thead>
        <tbody id="result-body">
            {% for num, id_person, id_applic in result %}
            <tr>
                <td>{{ num }}</td>
                <td>{{ id_person }}</td>
                <td>{{ id_applic }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

{% if user_role == 'admin' or user_role == 'operator' or user.is_superuser %}
<!-- Кнопка для выполнения действия -->
<button id="actionButton" type="button" class="btn btn-dark">Распределить</button>
<!-- Элемент для отображения сообщения -->
<div id="message" class="mt-3" style="display: none">Выполнено</div>
{% endif %}

<!-- Подключаем локальный файл jQuery -->
<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>

{% if user_role == 'admin' or user_role == 'operator' or user.is_superuser %}
<script>
    // нажатие кнопки
    document.getElementById("actionButton").addEventListener("click", function () {
        $.ajax({
            url: "{% url 'main:distribute_tasks' %}",
            type: "GET",
            success: function (data) {
                document.getElementById("message").style.display = "block";
                var resultBody = $("#result-body");
                resultBody.empty();
                data.result.forEach(function(item) {
                    resultBody.append(
                        "<tr><td>" + item.num + "</td><td>" + item.id_person + "</td><td>" + item.id_applic + "</td></tr>"
                    );
                });
            },
            error: function () {
                alert("Ошибка при распределении задач.");
            },
        });
    });
</script>
{% endif %}
{% endblock content %}

main/templates/main/scheduler_results.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-fluid" style="min-height: 80vh">
    <h3 class="text-center mb-4">Результаты Планировщика</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-3">
                <div class="card-body text-center">
                    <h2 class="card-title">Результаты</h2>
                    <pre id="scheduler-results">{{ results }}</pre>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}